# author Junji Takakura <j.takakura@gmail.com>

name: spine_core
description: The spine-core runtime provides functionality to load and manipulate Spine skeletal animation data using Dart.
version: 0.3.4
homepage: https://github.com/jtakakura/spine_core/

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
